source 'https://github.com/winfredzen/WZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'WZAuthorKit_Example' do
  pod 'WZAuthorKit', :path => '../'

  target 'WZAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
